apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hl57fq2tv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hl57fq2tv-go 
  name: hl57fq2tv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hl57fq2tv-go 
